config/routes.rb
Rails.application.routes.draw do
  # resources :resources, only: [:index, :new, :create, :destroy]
	root to: 'resources#index'

	resources :resources, only: [:index, :show, :new, :create]

	get 'cloudinary_index', to: 'resources#cloudinary_index'

	get 'pdfs', to: 'resources#pdfs'
	get 'images', to: 'resources#images'
	get 'new', to: 'resources#new'
	post '/new_upload', to: 'resources#new_upload'

	get 'load_resources', to: 'resources#load_resources'

	get '/destroy', to: 'resources#destroy'
	get '/confirm_destroy', to: 'resources#confirm_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord
	validates_uniqueness_of :public_id

	def self.load
		result = {}
		Resource.all.each{|r|r.delete}
		ActiveRecord::Base.connection.reset_pk_sequence!('resources')
		response = Cloudinary::Api.resources(resource: 'image', format: 'pdf', max_results: 500)		
		response['resources'].each do |resource|
			if !Resource.find_by_public_id(resource["public_id"])
				Resource.create(
					public_id: resource["public_id"].gsub('.pdf', ''), 
					width: 	resource["width"],
					height: resource["height"],
					format: resource["format"],
					url: resource["url"],
					secure_url: resource["secure_url"])
			end
		end
		result['cloud_resource_count'] = response['resources'].count
		result['db_resource_count'] = Resource.count
		result
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
	before_action :set_resource, only: [:show, :update, :destroy]

	def index
		data = Resource.load
		@cloud_resource_count = data["cloud_resource_count"]
		@db_resource_count = data["db_resource_count"]
		@resources = Resource.all.sort_by{|r| r.public_id}
	end

	def load_resources
		redirect_to '/resources'
	end

	def cloudinary_index
		res = Cloudinary::Api.resources(resource: 'image', format: 'pdf', max_results: 500)
		@resources = res['resources']
	end
	
	def show
	end
	
	def new 
		@resource = Resource.new
		render 'resources/new'
	end
	
	def create
		file =	Cloudinary::Uploader.upload(
			params["resource"]["file"], 
			:public_id => params["resource"]["file"].original_filename,
			:resource_type => :image,
			:chunk_size => 6_000_000
			)
 
			@resource = Resource.new(
				public_id: file["public_id"].gsub('.pdf', ''), 
				width: 	file["width"],
				height: file["height"],
				format: file["format"],
				url: file["url"],
				secure_url: file["secure_url"])

		# if @resource.save
		# 	redirect_to 'resources/show'
		# else 
			# redirect_to 'root_path'
			redirect_to 'cloudinary_index_path'
			# end
		end
		
		def destroy
			Cloudinary::Api.delete_resources(public_ids: params[:public_id])
			@resource = Resource.find_by_public_id(params["public_id"])
			redirect_to '/confirm_destroy'
	end

	def confirm_destroy
	end

	def pdfs
		res = Cloudinary::Api.resources(resource: 'image', format: 'pdf', max_results: 500)
		@pdfs = res['resources'].select{|r|r["format"]== 'pdf'}
		render 'resources/pdfs'
	end
	
	def images
		res = Cloudinary::Api.resources(resource: 'image', format: 'image', max_results: 500)
		@images = res['resources'].select{|r| ['jpg', 'png', 'bmp'].include?(r["format"])}
		render 'resources/images'
	end

	private
	def set_resource
		@resource = Resource.find_by_id(params["id"])
	end

	def resource_params
		params.require(:resource).permit(:public_id, :width, :height, :format, :url, :secure_url)
	end

	def local_image_path(name)
		Rails.root.join('uploads', name).to_s
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
			<li class="nav-item">
        <a class="nav-link" href="<%= cloudinary_index_path %>">CLOUDresources</a>
      </li>
			<li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">DBresources</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pdfs_path %>">Pdfs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= images_path %>">Images</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_path %>">New</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloudPrototypeV3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>

		<%= render partial: 'layouts/navbar' %>
		<%= yield %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/resources/_image_box.html.erb
<div>
  <div class="public_id">
    <%= upload["public_id"] %>
		<%= image_tag(upload["url"]) %>
		<%= link_to 'Delete image', resource_path(upload["public_id"]) + '/destroy', resource: upload,  method: 'DELETE' %>
	</div>
</div>

app/views/resources/cloudinary_index.erb
<% @resources.each do |res| %>
	<ul>
	<li>public_id: <%= res["public_id"] %></li>
	<li>format: <%= res["format"] %></li>
	<li>created_at: <%= res["created_at"] %></li>
	<li>width: <%= res["width"] %></li>
	<li>height: <%= res["height"] %></li>
	<li>url: <%= link_to 'show_image', res["url"] %></li>
	<li>secure_url: <%= res["secure_url"] %></li>
	<li><%= link_to 'Delete resource', destroy_path(res) %></li>
	<hr />
	</ul>
	<% end %>
<hr />
 

app/views/resources/confirm_destroy.html.erb
<h2>You have successfully deleted a resource.</h2>

app/views/resources/images.html.erb
<div class='row'>
	<div class='col-lg-12'>
	<ul>
	<% @images.each do |image| %>
		<%= render partial: 'image_box', locals: {upload: image} %>
		<hr />
		<% end %>
	</ul>
		</div>
</div>
 

app/views/resources/index.html.erb
<h1>Resources in database</h1>

	<p><%= link_to "Load resources from Cloudinary to local database", load_resources_path %></p>
	<% if @db_resource_count %>
		<p>DB Resource count: <%= @db_resource_count %></p>
	<% end %>
	<% if @cloud_resource_count %>
		<p>Cloud Resource count: <%= @cloud_resource_count %></p>
	<% end %>

<% @resources.each do |resource| %>
	<%= link_to resource.public_id, resource.secure_url %><br>
<% end %>

app/views/resources/index_cloudinary.html.erb
<h1>
  Uploads and Transformations
</h1>

<% @resources.each do |resource| %>
 
	Name: <%= resource["url"].split('/').last.gsub('%20', '') %>
	URL: <%= resource.secure_url %>
	 
<% end %>

app/views/resources/new.html.erb
<%= form_for @resource do |f| %>
	<%= f.label :file %>	
	<%= f.file_field :file %>	
	
	<%= f.submit %>
<% end %>

app/views/resources/pdfs.html.erb
<div class='row'>
	<div class='col-lg-12'>
	<% @pdfs.each do |pdf| %>
		<ul>
			<strong><li><%= link_to pdf["secure_url"].split('/').last.gsub('.pdf', '').gsub('%20', ' '), pdf["url"] %></li></strong>
			<li>format: <%= pdf["format"] %></li>
			<li>secure_url: <%= pdf["secure_url"] %></li>
		</ul>
		<hr />
		<% end %>
	</div>
</div>
 

app/views/resources/resource_not_created.html.erb
<h2>Resource NOT created.</h2>

app/views/resources/show.html.erb
	<h2><%= @resource.public_id %></h2>
	<%= @resource.url %>
	<%= @resource.secure_url %>
	<%= @resource.width %>
	<%= @resource.height %>
	<%= @resource.format %>
 

	<object data=`#{@resource.public_id}` type="application/pdf">
    <iframe src="https://docs.google.com/viewer?url=<%= `#{@resource.public_id}` %>&embedded=true"></iframe>
</object>